name: Auto Create PR

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - main
      - develop
  create:

jobs:
  check-if-renovate:
    runs-on: ubuntu-latest

    outputs:
      skip: ${{ steps.check_renovate.outputs.skip }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Check for renovate_bot commits
        id: check_renovate
        run: |
          AUTHOR=$(git log -1 --pretty=format:'%an')
          echo "Commit author: $AUTHOR"
          skip=false
          if [ "$AUTHOR" = "renovate[bot]" ]; then
            echo "Commit made by renovate_bot. Skipping PR changing."
            skip=true
          else
            skip=false
          fi
          echo "skip=$skip" >> "$GITHUB_OUTPUT"

  create-or-update-pr:
    runs-on: ubuntu-latest
    needs: check-if-renovate
    if: ${{ needs.check-if-renovate.outputs.skip != 'true' }}

    permissions:
      pull-requests: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit type
        id: commit_type
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true

      - name: Get PR tittle and body
        id: format_message
        env:
          EVENT_NAME: ${{ github.event_name }}
          TYPE: ${{ steps.commit_type.outputs.release_type }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          SKIP_CHANGE=$(./scripts/getPR.sh $TYPE $EVENT_NAME)
          TITLE=${GITHUB_REF#refs/heads/}
          echo "Current branch is $TITLE"
          echo "Change type is $TYPE"
          echo "Should I skip the change? $SKIP_CHANGE"
          echo "skip_change=$SKIP_CHANGE" >> "$GITHUB_OUTPUT"

      - name: Create PR
        if: ${{ github.event_name == 'create' && steps.format_message.outputs.skip_change != 'skip' }}
        env:
          OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create --reviewer $OWNER --base "develop" --draft --fill --body-file ./pr_body.md

      - name: Edit PR
        if: ${{ github.event_name == 'push' &&  steps.format_message.outputs.skip_change != 'skip' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit --body-file ./pr_body.md
